# version: '3.8' # docker compose v2开始不需要该字段，该字段会被认为冗余配置，会出现警告
services:
  nestjs_starter_test_postgres: # Needs updating (服务名称)
    image: postgres:alpine # (镜像)
    container_name: nestjs_starter_test_postgres # (容器名称)
    restart: always # (崩溃时重启服务)
    env_file:
      - .env.test
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5444:5432'
    volumes:
      - nestjs_starter_test_postgres_data:/var/lib/postgresql/data # Needs updating

  nestjs_starter_test_redis: # Needs updating
    image: redis:alpine
    container_name: nestjs_starter_test_redis # Needs updating
    ports:
      - '6380:6379'
    volumes:
      - nestjs_starter_test_redis_data:/data # Needs updating

networks:
  default:
    name: nestjs_starter # Needs updating

volumes:
  nestjs_starter_test_postgres_data: # Need updating
  nestjs_starter_test_redis_data: # Need updating
