# version: '3.8' # docker compose v2开始不需要该字段，该字段会被认为冗余配置，会出现警告
services:
  nestjs-url_postgres: # Needs updating (服务名称)
    image: postgres:alpine # (镜像)
    container_name: nestjs-url_postgres # (容器名称)
    restart: always # (崩溃时重启服务)
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - nestjs-url_postgres_data:/var/lib/postgresql/data # Needs updating

  nestjs-url_redis: # Needs updating
    image: redis:alpine
    container_name: nestjs-url_redis # Needs updating
    ports:
      - '6379:6379'
    volumes:
      - nestjs-url_redis_data:/data # Needs updating

networks:
  default:
    name: nestjs-url_dev # Needs updating

volumes:
  nestjs-url_postgres_data: # Need updating
  nestjs-url_redis_data: # Need updating
